train:
  seq_length: 512
  epochs: 100
  total_steps: 100000
  batch_size: 4

  checkpoint_interval: 500
  eval_interval: 500

  pipeline: "PromptPipeline"
  trainer: "AcceleratePPOTrainer"
  checkpoint_dir: "TODO"

model:
  model_path: "TODO"
  num_layers_unfrozen: 2

tokenizer:
  tokenizer_path: "gpt2"
  truncation_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.01

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000
    eta_min: 5.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 128
  chunk_size: 16
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 4
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.2
  scale_reward: "running"
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 256
